blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),
     path('home1/', views.home1, name='home1'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField


def user_directory_path(instance, filename):
    return 'posts/%Y/%m/%d/'.format(instance.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    image = models.ImageField(
        upload_to=user_directory_path, default='posts/default.jpg')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = RichTextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    def get_absolute_url(self):
        return reverse('blog:post_single', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['publish']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Comment, Category
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'email': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)


class PostSearchForm(forms.Form):
    q = forms.CharField()
    c = forms.ModelChoiceField(
        queryset=Category.objects.all().order_by('name'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['c'].label = ''
        self.fields['c'].required = False
        self.fields['c'].label = 'Category'
        self.fields['q'].label = 'Search For'
        self.fields['q'].widget.attrs.update(
            {'class': 'form-control menudd'})
        self.fields['q'].widget.attrs.update(
            {'data-toggle': 'dropdown'})

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Post, Comment, Category
from .forms import NewCommentForm, PostSearchForm
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.core import serializers
from django.http import JsonResponse


def home(request):

    all_posts = Post.newmanager.all()

    return render(request, 'index.html', {'posts': all_posts})

def home1(request):

    all_posts = Post.newmanager.all()

    return render(request, 'home1.html', {'posts': all_posts})


def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'single.html', {'post': post, 'comments':  user_comment, 'comments': comments, 'comment_form': comment_form, 'allcomments': allcomments, })


class CatListView(ListView):
    template_name = 'category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content


def category_list(request):
    category_list = Category.objects.exclude(name='default')
    context = {
        "category_list": category_list,
    }
    return context


def post_search(request):
    form = PostSearchForm()
    q = ''
    c = ''
    results = []
    query = Q()

    if request.POST.get('action') == 'post':
        search_string = str(request.POST.get('ss'))

        if search_string is not None:
            search_string = Post.objects.filter(
                title__contains=search_string)[:5]

            data = serializers.serialize('json', list(
                search_string), fields=('id', 'title', 'slug'))

            return JsonResponse({'search_string': data})

    if 'q' in request.GET:
        form = PostSearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            c = form.cleaned_data['c']

            if c is not None:
                query &= Q(category=c)
            if q is not None:
                query &= Q(title__contains=q)

            results = Post.objects.filter(query)

    return render(request, 'search.html',
                  {'form': form,
                   'q': q,
                   'results': results})

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %} Welcome to blog {% endblock %}</title>
    
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
    />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg ">
        <div class="container">
        <a class="nav-logo1" href="/">
          <img src="../../static/logo-tp1.png" alt="logo" class="nav-logo">
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="40"
              height="40"
              fill="#fff"
              class="bi bi-list"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
              /> </svg>
          </span>
        </button>
        <div class="collapse navbar-collapse navbar-nav" id="navbarTogglerDemo02">
            <div class="dropdown me-auto mb-2 mb-lg-0 ">
              <a
                class="navbar-link dropdown-toggle nav-item"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-expanded="false"
                >Categories</a
              >
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for category in category_list %}

                <a class="dropdown-item" href="/category/{{ category.name}}">
                  {{ category.name|title }}
                </a>
                {% endfor %}
              </div>
            </div>
          <form class="d-flex righty" method="get">
            <div class="input-group">
              <input
                type="search"
                name="q"
                class="form-control form-control-lg"
                placeholder="Search"
                aria-label="search"
                aria-describedby="button-addon2"
              />
              <button class="btn btn-light" id="button-addon2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  fill="currentColor"
                  class="bi bi-search"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"
                  />
                </svg>
              </button>
            </div>
          </form>
        </div>
      </div>
      </nav>
    </header>

    <div class="container">{% block content %} {% endblock %}</div>

    <div class="footerr">
      <p>
        Copyright &copy; 2021 All Rights Reserved. Designed by
        <a href="https://dnawebdesign.com.au" class="footer-link"
          >DNAWEBDESIGN</a
        >
      </p>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

blog/templates/category.html
{% extends "base.html" %} {% block title %} Catlist {% endblock %} {% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  


  <div class="main-p">
    <div class="cat-head">
      <h1>List of {{catlist.cat}} Posts</h1>

    </div>
    
    <div class="grid-cards">
      {% for post in catlist.posts %}
      <div class="grid-cols">
        <a class="link-col" href="{{post.get_absolute_url}}">
          <div class="grid-item">
            <img
              class="grid-img"
              src="{{post.image.url}}"
              alt="{{ post.title }}"
            />
            <h5>{{post.title|truncatechars:40}}</h5>
            <p class="grid-text">{{post.excerpt|truncatechars:40}}</p>
            <div class="grid-date"><small>{{post.publish}}</small></div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>


{% endblock %}

blog/templates/index.html
{% extends "base.html" %} {% block title %} Welcome to Blog {% endblock %}
 {% block content %}

{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'style.css' %}">

<style>


</style>
  <div class="main-p">
    <div class="banner">
      <img src="../../static/banner.png" class='banner-img' alt="sql banner">
    </div>
    <div class="grid-cards">
      {% for post in posts %}
      <div class="grid-cols">
        <a class="link-col" href="{{post.get_absolute_url}}">
          <div class="grid-item">
            <img
              class="grid-img"
              src="{{post.image.url}}"
              alt="{{ post.title }}"
            />
            <h5>{{post.title|truncatechars:40}}</h5>
            <p class="grid-text">{{post.excerpt|truncatechars:40}}</p>
            <div class="grid-date"><small>{{post.publish}}</small></div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  
</div>
{% endblock %}

blog/templates/search.html
{% extends "base.html" %}
{% block title %}Search Page{% endblock %}
{% block content %}

<style>
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
    ::-webkit-scrollbar{
        display: none;
    }
.main{
    margin: 80px 20px;
    height: 100vh;
    /* overflow: hidden; */
}
.grid-cards {
    height: auto;
      display: grid;
      grid-template-columns: auto auto auto;
      justify-content: space-between;
      align-content: start;
      grid-gap: 30px;
    }

    
    .grid-cols {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
      width: 350px;
      height: 400px;
      border-radius: 6px;
      transition: .3s ease;
    }
    .grid-cols:hover{
      transform: scale(1.02);
    }
    .grid-item{
       display: flex;
       flex-direction: column;
       justify-content: space-between;
       flex-wrap: nowrap;
       height: 100%;
       width: 100%;
       color: rgb(26, 26, 26);
      
    }

    .grid-img {
      width: 100%;
      height: 200px;
      border-top-left-radius: 6px;
      border-top-right-radius: 6px;
    }
    
    .grid-item > p,h6,small {
          padding:0 20px;
          color: rgb(15, 15, 15);
        }
    
    .grid-date {
      border-top: 1px solid rgb(207, 207, 207);
      padding-bottom: 1rem;
    }
    .link-col:hover {
      text-decoration: none;
    }
    .grid-item h6 {
      text-transform: capitalize;
      font-weight: bold;
    }
    .submit-btn{
        margin-top: 20px;
        padding: 8px 20px;
        background-color: #71bfff;
        color: #ffffff;
        border: none;
        border-radius: 6px;
    }
    .cat-drop{
       
        margin-top: 20px;
        
    }

</style>
<div class="container ">
<div class="main">
    {% if q %}
    <h1>Posts containing "{{ q }}"

        {% if c %}
        In category "{{ c }}"
        {% endif %}

    </h1>
    <p>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </p>


    
            <div class="grid-cards">
                {% for post in results %}
                <div class="grid-cols">
                    <a class="link-col" href="{{post.get_absolute_url}}">
                        <div class="grid-item">
                          <img
                            class="grid-img"
                            src="{{post.image.url}}"
                            alt="{{ post.title }}"
                          />
                          <h6>{{post.title|truncatechars:40}}</h6>
                          <p class="grid-text">{{post.excerpt|truncatechars:40}}</p>
                         <div class="grid-date"><small >published on: {{post.publish}}</small></div> 
                        </div>
                      </a>
                </div>
                
                {% empty %}
                <p>There are no results for your query.</p>
                {% endfor %}
            </div>
        </div>
    </div>


    <p><a href="{% url "blog:post_search" %}" class="btn btn-primary" role="button" aria-disabled="true">New
            Search</a>
    </p>
    {% else %}
    <div class="main">
    <h1>Search for Posts</h1>
    <form class="dropdown" method="get">
        {% csrf_token %}
        <div>{{ form.q }}</div>

        <ul class="dropdown-menu col-12 pl-2" role="menu" aria-labelledby="menu" id="list">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">HTML</a></li>
            <div class="dropdown-divider"></div>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">CSS</a></li>
            <div class="dropdown-divider"></div>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">JavaScript</a></li>
        </ul>
<div class="cat-drop">
        {{ form.c }}
    </div>
        <button type="submit" class="submit-btn">Submit</button>
    </form>
    {% endif %}
</div>
</div>
</div>

<script>
    $(document).on('keyup', '#id_q', function (e) {
        e.preventDefault();

        var minlength = 3;
        var results = [];

        if ($('#id_q').val().length >= minlength) {
            $.ajax({
                type: 'POST',
                url: '{% url "blog:post_search" %}',
                data: {
                    ss: $('#id_q').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {

                    $.each(JSON.parse(json.search_string), function (i, item) {

                        results.push('<li class="my-2 pl-2"><a href="/' + item
                            .fields.slug +
                            '">' + item.fields.title +
                            '</a></li>')
                    })

                    if (!$(".show")[0]) {
                        $('.menudd').trigger('click')
                    }

                    document.getElementById("list").innerHTML = (!results.length) ?
                        "No results match your query" : results.join('');
                },
                error: function (xhr, errmsg, err) {}
            });
        }
    })
</script>




{% endblock %}

blog/templates/single.html
{% extends "base.html" %} {% block title %}{{post.title}} {% endblock %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  
<link
  rel="stylesheet"
  href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/default.min.css"
/>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>



  <div class="single-p">
    <img class="post-img"  src="{{post.image.url}}" alt="{{ post.title }}">
    <div class="post-content">
      
        <h1>{{post.title}}</h1>
        <p>{{post.content|safe}}</p>
        <div class="grid-date"><small>{{post.publish}}</small></div> 
    </div>

    <div class="comment-section">

      {% with allcomments.count as total_comments %}
      <h5>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h5>
      {% endwith %}

      {% load mptt_tags %}

      <div class="comments-box">
        {% recursetree comments %}
        <div id="{{ node.id }}" class="comment-card">
          <div class="comment-text">
            <h6>By {{ node.name }} | </h6>
            <span> {{ node.publish }}</span>
            <p>{{node.content}}</p>
           </div>
          
          
          {% if node.level < 3 %}
          <button class="comment-reply" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      
        <form class="myForm" id="myForm" method="post">
          <h3>Leave a comment</h3>
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="submit-btn">Submit</button>
        </form>
    

    </div>
  </div>

<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">Email:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

{% endblock %}